apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: branch-tls-external
  labels:
    cert-manager.io/solver: route53
spec:
  commonName: "*.uat.sas-notprod.homeoffice.gov.uk"
  dnsNames:
  - "*.uat.sas-notprod.homeoffice.gov.uk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: branch-tls-external
