apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: file-vault-ingress-{{ .DRONE_SOURCE_BRANCH }}
  {{ file .FILEVAULT_INGRESS_EXTERNAL_ANNOTATIONS | indent 2 }}
  {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
  name: file-vault-ingress
  {{ file .FILEVAULT_INGRESS_EXTERNAL_ANNOTATIONS | indent 2 }}
  {{ else }}
  name: file-vault-ingress
  {{ file .FILEVAULT_INGRESS_EXTERNAL_ANNOTATIONS_PROD | indent 2 }}
  {{ end }}

spec:
  {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
  ingressClassName: nginx-internal
  {{ else }}
  ingressClassName: nginx-external
  {{ end }}
  tls:
  - hosts:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - fv-{{ .DRONE_BUILD_NUMBER }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
    - fv-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - fv-{{ .APP_NAME }}.uat.sas-notprod.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
    - fv-{{ .APP_NAME }}.sas.homeoffice.gov.uk
    {{ end }}
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    secretName: branch-tls-external
    {{ if else .KUBE_NAMESPACE .UAT_ENV }}
    secretName: file-vault-cert
    {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
    secretName: branch-tls-internal
    {{ end }}
  rules:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  - host: fv-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
  {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
  - host: fv-{{ .APP_NAME }}.uat.sas-notprod.homeoffice.gov.uk
  {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
  - host: fv-{{ .APP_NAME }}.sas.homeoffice.gov.uk
  {{ end }}
    http:
      paths:
      - path: /
        backend:
          {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
          serviceName: file-vault-{{ .DRONE_SOURCE_BRANCH }}
          {{ else }}
          serviceName: file-vault
          {{ end }}
          servicePort: 10443
