apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: file-vault-allow-ingress-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: file-vault-allow-ingress
  {{ end }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          # This is temporary change using ingress internal for prod. We will revert back the change after PECC expires
          # https://support.acp.homeoffice.gov.uk/servicedesk/customer/portal/1/ACP-19781
          {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
          name: ingress-internal
          {{ else }}
          name: ingress-external
          {{ end }}
    ports:
    - port: 10080
      protocol: TCP
    - port: 10443
      protocol: TCP
  podSelector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: file-vault-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: file-vault
      {{ end }}
  policyTypes:
  - Ingress
